apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: user18-dotnet-app-
spec:
  params:
    - name: GIT_URL
      value: "https://github.com/rondragon/dotnet-app"
    - name: REGISTRY
      value: rondragon
    - name: IMAGE_NAME
      value: dotnet-app
    - name: IMAGE_TAG
      value: v6
    - value: user18-application
  pipelineRef:
    name: user18-dotnet-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: storage
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Mi
          volumeMode: Filesystem
